apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pinger
  template:
    metadata:
      labels:
        app: pinger
    spec:
      containers:
        - name: pinger
          image: reseltraining/pinger:XX_VERSION_XX
          ports:
            -
              containerPort: 3000
          env:
            - name: CURRENT_VERSION
              value: v1
